build_run:
		docker build . -t gotraining:dev
		docker run -it gotraining:dev
build:
		docker build . -t gotraining:dev
run:
		docker run -it goTraining:dev
run_into:
		docker run -it goTraining:dev /bin/bash
run_test:
		docker run -it goTraining:dev go test